### ISSUE TITLE
Invalid input does not always trigger errors in the log

### ISSUE THREAD

**Issue by unw9527** [xlab-uiuc/acto#112]
**What version of operator are you using?**
commit 561cf47d783c368fd8795acb82a5a39099a35984 (HEAD -> master)

**What operating system and processor architecture are you using (`kubectl version`)?**
MacOS. x86. 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-19T19:53:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**

I am testing whether an automating testing tool can detect the errors in the log. I first applied the operator yaml file and crd yaml file. Then I applied the following custom resource file as follows:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: test-cluster
spec:
  additionalLabels:
    crdb: is-cool
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v21.2.10
  nodes: 3
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  tlsEnabled: true
```

(All files were applied using `kubectl apply -f <filename> -n cockroach-operator-system`)

After doing this, I got the log using kubernetes python client (`read_namespaced_pod_log`) to check whether there were errors. And there were no harmful errors. Then I deployed another custom resource file (basically, adding `hostPath` to `dataStore`), as follows:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: test-cluster
spec:
  additionalLabels:
    crdb: is-cool
  dataStore:
    hostPath:
      path: ugrpoqibzr
      type: cvkprdlnkt
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v21.2.10
  nodes: 3
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  tlsEnabled: true
```
After using `kubectl apply -f <filename> -n cockroach-operator-system`, I got the log using kubernetes python client again.

**What did you expect to see?**

I expect to see errors indicating that the field I added is invalid (i.e. "one of HostPath or VolumeClaim should be set"), since the crd requires that only one of `pvc` and `hostPath` should be set. I checked the source code of cockroachdb-operator and indeed an error message will be thrown if both `pvc` and `hostPath` are specified.

**What did you see instead?**
I cannot always see the error message indicating that "one of HostPath or VolumeClaim should be set". This error message is often lost in the log.
