### ISSUE TITLE
Weird behavior when getting the custom resource object from k8s server

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#12]
We get the custom resource object from k8s server after each test to compute the delta. When I was inspecting the deltas, I realized some strange changes:

This is the initial CR yaml we submit:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
spec:
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
  tls:
    caSecretName: null
    disableNonTLSListeners: false
    secretName: null
  skipPostDeploySteps: false
  tolerations: null
```

After submit this CR yaml, the custom resource object we get from the k8s server is:
```json
"resources": {
    "limits": {
        "cpu": "1",
        "memory": "4Gi"
    },
    "requests": {
        "cpu": "1",
        "memory": "4Gi"
    }
},
"secretBackend": {},
"service": {
    "type": "ClusterIP"
},
"terminationGracePeriodSeconds": 604800,
"tls": {}
```

Note that the `cpu` fields under `resources/limits` and `resources/requests` are strings, and `tls` is empty while we specified `disableNonTLSListeners: false` in our CR yaml. The response also misses `skipPostDeploySteps`, while our CR yaml input has `skipPostDeploySteps: false`.

Then, if we change the `resources/limits/cpu` to 2, and submit the changed CR yaml, the custom resource object we get from k8s server will be:
```json
"resources": {
    "limits": {
        "cpu": 2,
        "memory": "4Gi"
    },
    "requests": {
        "cpu": 1,
        "memory": "4Gi"
    }
},
"secretBackend": {},
"service": {
    "type": "ClusterIP"
},
"skipPostDeploySteps": false,
"terminationGracePeriodSeconds": 604800,
"tls": {
    "disableNonTLSListeners": false
}
```
Note that the `cpu` fields under `resources/limits` and `resources/requests` are integers now, and it now reflects `disableNonTLSListeners: false` and `"skipPostDeploySteps": false`.

It's hard for me figure out why this happens, and it currently interferes our system state delta.

One guess I have is that `false` is probably the `omitempty` value for bool variables, and they are omitted when the server dumps the CR spec. And when we change the `resources/limits/cpu` field, it triggered the server to dump the CR spec in a different way.
