### ISSUE TITLE
[percona-server-mongodb-operator] Configuring the storage options through `spec.mongod.storage.*` does not have any effect

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#163]
## Description
We were trying to set the storage configurations through the `spec.mongod.storage.*` fields, but we found that these fields to be ineffective. We checked through code and found that there is no place in the source code that accesses these fields except in the `CheckNSetDefaults` function, which only setting default values for the `spec.mongod.storage` field.

### Expectation
We expected that our configuration in the `spec.mongod.storage.*` fields will be reflected in the statefulSet. If this field's functionality has been removed, we think these fields should be removed from the CRD, since CRD is the exposed API for configuring the Mongodb cluster

### Reproduce
1. Deploy the percona-server-mongodb-operator
2. Deploy a mongodb cluster instance through some minimum CR, with the `spec.mongod.storage.*` configured to use `inMemory` option:
```yaml
apiVersion: psmdb.percona.com/v1-12-0
kind: PerconaServerMongoDB
metadata:
  name: minimal-cluster
spec:
  crVersion: 1.12.0
  image: percona/percona-server-mongodb:5.0.7-6
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: 5.0-never
    schedule: "0 2 * * *"
  secrets:
    users: minimal-cluster
  replsets:

  - name: rs0
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi

  sharding:
    enabled: true

    configsvrReplSet:
      size: 1
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi

    mongos:
      size: 1
  mongod:
    security:
      encryptionKeySecret: "my-cluster-name-mongodb-encryption-key"
    storage:
      engine: inMemory
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
```
3. Check the created statefulset's container args, and the storage engine used is still the default option: `wiredTiger`

### Root cause
We checked the code and found that the fields `spec.mongod.storage.*` never get used except when setting default values. This causes these fields to be ineffective. If functionality has been removed, the `MongodSpecStorage` field under `MongodSpec` should be removed.

## Environment
* Kubernetes version information:

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-10T18:26:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
