### ISSUE TITLE
[Xtradb] Using `SmartUpdate` leads to irrecoverable PXC cluster

### ISSUE THREAD

**Issue by Essoz** [xlab-uiuc/acto#193]
#### Summary

When using `SmartUpdate`, the operator always waits for the statefulset to become ready before updating pods with new specs. This behavior can make system failures irrecoverable.

#### Priority 

Critical

#### Description

- What Happened?

  Whenever statefulsets fall into an unready state and the `SmartUpdate` upgrade strategy is used, the operator keeps waiting for them to get ready before applying the new spec from CR, as indicated in the source code: https://github.com/percona/percona-xtradb-cluster-operator/blob/main/pkg/controller/pxc/upgrade.go#L279-L282

In scenarios where the statefulsets cannot get ready by themselves, the operator will stuck forever waiting without applying the new custom resource, preventing users from attempting mission-critical operations such as fail-recovery by modifying their custom resources.

Examples of such scenarios include:
1. Due to system environment changes (e.g. a crashing node) and the affinity rules, a new pod cannot be scheduled, falling into the "pending" state. Users may want to change the affinity rules to fix the situation but this is not possible due to the stuck operator.
2. Due to a misconfiguration introduced when upgrading the system, a PXC pod can never get spawned successfully, which then falls into the unready state. Users may want to fix the misconfiguration but this is not possible due to the stuck operator.

- To Reproduce, 
  We will demonstrate how to represent this using the aforementioned "misconfiguration" scenario.

  1. Deploy the operator.
  2. Deploy a simple PXC cluster by applying the following custom resource.

```yaml
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  crVersion: 1.12.0
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    autoRecovery: true
    livenessDelaySec: 200
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
    resources:
      requests:
        memory: 100M
        cpu: 200m
  backup:
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup
    storages:
      s3-us-west:
        type: s3
        verifyTLS: true
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
      azure-blob:
        type: azure
        azure:
          credentialsSecret: azure-secret
          container: test
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 6G
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: s3-us-west
      - name: "daily-backup"
        schedule: "0 0 * * *"
        keep: 5
        storageName: fs-pvc
```

3. Adding a misconfiguration to our CR file and re-apply. The misconfiguration here refers to the entry `disktype: do_not_exist` inside `cr.pxc.nodeSelector`

```yaml
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  crVersion: 1.12.0
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.27-18.1
    autoRecovery: true
    livenessDelaySec: 200
    nodeSelector:
      disktype: do_not_exist # misconfiguration
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
    resources:
      requests:
        memory: 100M
        cpu: 200m
  backup:
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup
    storages:
      s3-us-west:
        type: s3
        verifyTLS: true
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
      azure-blob:
        type: azure
        azure:
          credentialsSecret: azure-secret
          container: test
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 6G
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        storageName: s3-us-west
      - name: "daily-backup"
        schedule: "0 0 * * *"
        keep: 5
        storageName: fs-pvc
```

4. Observe that the pod `cluster1-pxc-2` falls into pending state:

```bash
> kubectl get pod/cluster1-pxc-2

NAME             READY   STATUS    RESTARTS   AGE
cluster1-pxc-2   0/3     Pending   0          69m
```

5. Now apply the first CR to get rid of the misconfiguration. 

Observe that the `statefulset.apps/cluster1-pxc`'s spec is changed accordingly, but the pod `cluster1-pxc-2` still has the wrong spec and is in pending state.

Furthermore, dump the logs of the operator and observe the repeated logs indicating that the operator is waiting for the statefulset to get ready :

```bash
> kubectl logs deployment.apps/percona-xtradb-cluster-operator

...
{"level":"info","ts":1669232075.0910985,"logger":"perconaxtradbcluster","caller":"pxc/upgrade.go:280","msg":"can't start/continue 'SmartUpdate': waiting for all replicas are ready","cluster":"cluster1","namespace":"default"}
{"level":"info","ts":1669232080.2320209,"logger":"perconaxtradbcluster","caller":"v1/pxc_types.go:972","msg":"Cluster size will be changed from 2 to 3 due to safe config","cluster":"cluster1","namespace":"default"}
{"level":"info","ts":1669232080.2320888,"logger":"perconaxtradbcluster","caller":"v1/pxc_types.go:973","msg":"Set allowUnsafeConfigurations=true to disable safe configuration","cluster":"cluster1","namespace":"default"}
{"level":"info","ts":1669232081.3221653,"logger":"perconaxtradbcluster","caller":"pxc/upgrade.go:267","msg":"statefulSet was changed, run smart update","cluster":"cluster1","namespace":"default"}
{"level":"info","ts":1669232081.3222878,"logger":"perconaxtradbcluster","caller":"pxc/upgrade.go:280","msg":"can't start/continue 'SmartUpdate': waiting for all replicas are ready","cluster":"cluster1","namespace":"default"}
...
```

#### Regression Issue

No

#### Found By Automation

Yes

#### Environment

```shell
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-19T19:53:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

operator version: v1.11.0
```
