### ISSUE TITLE
[BUG] mongodb-kubernetes-operator: operator crashes when spec.security is empty

### ISSUE THREAD

**Issue by taham0** [xlab-uiuc/acto#198]
**What did you do to encounter the bug?**
I was trying to create a mongodb cluster by submitting an CR with the field `spec.security` set to {}. When this field is unmarshalled by golang, `spec.security.authentication.modes` results in an empty array. 

1. Apply the following spec with the field `spec.security` set to {}: 

```yaml
spec:
  members: 3
  security: {}
  users:
  - db: admin
    name: my-user
    passwordSecretRef:
      name: my-user-password
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    scramCredentialsSecretName: my-scram
  type: ReplicaSet
  version: 4.4.0
```

**What did you expect?**
The operator should capture that the array is empty and not crash.

**What happened instead?**
The operator crashes with the following error:

> panic: runtime error: index out of range [0] with length 0

When setting the `AutoAuthMechanism` the operator tries to assign the first authentication mode at the 0th index of the Modes array. Since the array is empty, the index is out of range.

**Operator Information**

- Operator Version - `0.7.4`
- MongoDB Image used - `4.4.0`

**Kubernetes Cluster Information**

<details>
<summary><code>kubectl version --short --output=yaml</code></summary>
<br><pre>
$ kubectl version --short --output=yaml
clientVersion:
  buildDate: "2022-05-24T12:26:19Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2021-05-21T23:01:33Z"
  compiler: gc
  gitCommit: 5e58841cce77d4bc13713ad2b91fa0d961e69192
  gitTreeState: clean
  gitVersion: v1.21.1
  goVersion: go1.16.4
  major: "1"
  minor: "21"
  platform: linux/amd64
</pre>
</details>

**Additional context**

When setting the AutoAuthMechanism the operator tries to assign the first authentication mode at the 0th index of the Modes array. Since the array is empty, the index is out of range.

### Possible root cause and fix

The root cause is essentially the same as:
- https://github.com/mongodb/mongodb-kubernetes-operator/issues/1055
