### ISSUE TITLE
Bug report: Alarm is not fired for certain detected bugs

### ISSUE THREAD

**Issue by Spedoske** [xlab-uiuc/acto#224]
I was trying to reproduce two bugs of the three detected bugs in Rabbitmq Operator, which is documented in `bugs.md`.
https://github.com/rabbitmq/cluster-operator/issues/992
https://github.com/rabbitmq/cluster-operator/issues/928

## Bug #992

Acto changed `storageClassName`, and there is no changes in PVC. So there should be an alarm for inconsistency.
(trial-00-0006)

```
---------- INPUT DELTA  ----------
{
      "values_changed": {
            "root['spec']['persistence']['storageClassName']": {
                  "prev": "standard",
                  "curr": "ACTOKEY",
                  "path": [
                        "spec",
                        "persistence",
                        "storageClassName"
                  ]
            }
      }
}
---------- SYSTEM DELTA ----------
{
      "pod": {},
      "deployment_pods": {},
      "stateful_set": {},
      "deployment": {},
      "config_map": {},
      "service": {},
      "service_account": {},
      "pvc": {},
      "cronjob": {},
      "ingress": {},
      "network_policy": {},
      "pod_disruption_budget": {},
      "secret": {},
      "endpoints": {},
      "job": {},
      "role": {},
      "role_binding": {},
      "custom_resource_spec": {
            "values_changed": {
                  "root['persistence']['storageClassName']": {
                        "prev": "standard",
                        "curr": "ACTOKEY",
                        "path": [
                              "persistence",
                              "storageClassName"
                        ]
                  }
            }
      },
      "custom_resource_status": {}
}
```

## Bug # 928
The state 1 is shown as the following yaml file.
(trial-02-0023)
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: null
  imagePullSecrets: null
  override:
    statefulSet:
      spec:
        template:
          spec:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - test-cluster
                  topologyKey: kubernetes.io/hostname
            containers: []
  ... omitted ...
```
The state 2 is shown as the following yaml file.
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: rabbitmq-system
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: null
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - test-cluster
        topologyKey: kubernetes.io/hostname
  image: null
  imagePullSecrets: null
  override:
    statefulSet:
      spec:
        template:
          spec:
            affinity: null
            containers: []
```

We found that `override.statefulSet.spec.template.spec.affinity` become `null`, but there is no change in system delta.
```
---------- SYSTEM DELTA ----------
{
      "pod": {},
      "deployment_pods": {},
      "stateful_set": {},
      "deployment": {},
      "config_map": {},
      "service": {},
      "service_account": {},
      "pvc": {},
      "cronjob": {},
      "ingress": {},
      "network_policy": {},
      "pod_disruption_budget": {},
      "secret": {},
      "endpoints": {},
      "job": {},
      "role": {},
      "role_binding": {},
      "custom_resource_spec": {
            "dictionary_item_removed": {
                  "root['override']['statefulSet']['spec']['template']['spec']['affinity'][podAntiAffinity][requiredDuringSchedulingIgnoredDuringExecution][0][labelSelector][matchExpressions][0][key]": {
                        "prev": "app.kubernetes.io/name",
                        "curr": "NotPresent",
                        "path": [
                              "override",
                              "statefulSet",
                              "spec",
                              "template",
                              "spec",
                              "affinity",
                              "podAntiAffinity",
                              "requiredDuringSchedulingIgnoredDuringExecution",
                              0,
                              "labelSelector",
                              "matchExpressions",
                              0,
                              "key"
                        ]
                  },
                  "root['override']['statefulSet']['spec']['template']['spec']['affinity'][podAntiAffinity][requiredDuringSchedulingIgnoredDuringExecution][0][labelSelector][matchExpressions][0][operator]": {
                        "prev": "In",
                        "curr": "NotPresent",
                        "path": [
                              "override",
                              "statefulSet",
                              "spec",
                              "template",
                              "spec",
                              "affinity",
                              "podAntiAffinity",
                              "requiredDuringSchedulingIgnoredDuringExecution",
                              0,
                              "labelSelector",
                              "matchExpressions",
                              0,
                              "operator"
                        ]
                  },
                  "root['override']['statefulSet']['spec']['template']['spec']['affinity'][podAntiAffinity][requiredDuringSchedulingIgnoredDuringExecution][0][labelSelector][matchExpressions][0][values][0]": {
                        "prev": "test-cluster",
                        "curr": "NotPresent",
                        "path": [
                              "override",
                              "statefulSet",
                              "spec",
                              "template",
                              "spec",
                              "affinity",
                              "podAntiAffinity",
                              "requiredDuringSchedulingIgnoredDuringExecution",
                              0,
                              "labelSelector",
                              "matchExpressions",
                              0,
                              "values",
                              0
                        ]
                  },
                  "root['override']['statefulSet']['spec']['template']['spec']['affinity'][podAntiAffinity][requiredDuringSchedulingIgnoredDuringExecution][0][topologyKey]": {
                        "prev": "kubernetes.io/hostname",
                        "curr": "NotPresent",
                        "path": [
                              "override",
                              "statefulSet",
                              "spec",
                              "template",
                              "spec",
                              "affinity",
                              "podAntiAffinity",
                              "requiredDuringSchedulingIgnoredDuringExecution",
                              0,
                              "topologyKey"
                        ]
                  }
            }
      },
      "custom_resource_status": {}
}
```

So there should be an alarm for inconsistency, but Acto did not alarm.
