### ISSUE TITLE
Port cloudnative-pg Operator

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#282]
https://github.com/cloudnative-pg/cloudnative-pg

**Comment by tylergu** [comment]
# [Bug]: Unable to recover the cluster after it gets into error state

## What happened
We deployed the cluster with the example YAML from the repository. The operator successfully deploys the Postgres cluster according the desired state.
Then we issued a misoperation, by changing the Affinity to one which cannot be satisfied currently in our Kubernetes cluster. We observe that the operator updates the Pods with the erroneous Affinity rule, and the restarted pods cannot be scheduled.

Then we tries to fix the Affinity in the CR by reverting it back to the previous valid one. However, after applying the fixed CR with the correct Affinity rule, the operator is stuck and never updates the Pods.

We looked into the source code of the operator, and we think the root cause of this bug is caused by the logic to check if a pod is ready before rolling out: https://github.com/cloudnative-pg/cloudnative-pg/blob/10611d99b1846fbd7100dbd4769f3fca6cdd4337/controllers/cluster_upgrade.go#L246
In this case, the Pod is in a permanent error state, and it is not ready. So the operator skips rolling this erroneous Pod with the fixed Affinity rule.

This prevents us from recovering the cluster back to healthy state after some misoperation, or even just some Kubernetes topology changes. For example, if the Kubernetes topology changed and caused the existing Affinity rule to not be able to satisfied, we cannot correct the Affinity rule in the CR to save the cluster.

We also experimented this with other properties in the CR, and this bug is vulnerable not only to Affinity, but also all error states caused by other misoperations such as misconfigured containter spec, volume spec, and etc.

## Cluster resource
Initial CR:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-example-app-user
  description: Example of cluster
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
```

Then we apply:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  affinity:
    enablePodAntiAffinity: true
    nodeSelector:
      SOMESELECTOR: BAR
    topologyKey: failure-domain.beta.kubernetes.io/zone
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-example-app-user
  description: Example of cluster
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
```

Then we fix the erroneous Affinity rule by reverting the CR:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-example-app-user
  description: Example of cluster
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
```

## Relevant log output
--- After applying the erroneous Affinity change
{"level":"info","ts":"2023-12-01T04:33:10Z","logger":"cluster-resource","msg":"validate update","version":"v1","name":"test-cluster","namespace":"cnpg-system"}
{"level":"info","ts":"2023-12-01T04:33:10Z","msg":"Pod rollout required","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"1177953c-4cfd-4e74-aa14-181f08bd9db5","uuid":"bb4da85c-9002-11ee-bd59-aed01ababf32","pod":"test-cluster-3","reason":"original and target PodSpec differ in node-selector"}
{"level":"info","ts":"2023-12-01T04:33:10Z","msg":"Recreating instance pod","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"1177953c-4cfd-4e74-aa14-181f08bd9db5","uuid":"bb4da85c-9002-11ee-bd59-aed01ababf32","pod":"test-cluster-3","to":"ghcr.io/cloudnative-pg/postgresql:16.1","reason":"Restarting instance test-cluster-3, because: original and target PodSpec differ in node-selector"}
{"level":"info","ts":"2023-12-01T04:33:11Z","msg":"Creating new Pod to reattach a PVC","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"c02ef355-37f1-4323-8729-c35517a37287","uuid":"bbf3b697-9002-11ee-bd59-aed01ababf32","pod":"test-cluster-3","pvc":"test-cluster-3"}
--- After reverting to valid CR
{"level":"info","ts":"2023-12-01T04:34:14Z","logger":"cluster-resource","msg":"validate update","version":"v1","name":"test-cluster","namespace":"cnpg-system"}

**Comment by tylergu** [comment]
Acto also detect the bug in the operator, where it is unable to delete annotations and labels.
However, such limitation is already documented in the operator manual: https://cloudnative-pg.io/documentation/1.21/labels_annotations/

**Comment by tianyin** [comment]
So you find two bugs there?

**Comment by tylergu** [comment]
# [Bug]: Operator Keeps Recreating Pods when Deleting `sources` in `projectedVolumeTemplate`

## What happened
Operator keeps recreating postgres pods, causing the Postgres cluster to run in a permanent erroneous, misconfigured state. It happens when we try to delete the `sources` in the `projectedVolumeTemplate`.

The operator keeps recreating pods with the log message "Pod rollout required" and "Recreating instance pod". And the reason from the log message is 
```
"Restarting instance test-cluster-3, because: projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"
```

Apparently the operator is having a bug in the `checkProjectedVolumeIsOutdated` function, where is DeepEqual function is not working properly.

## Cluster resource
First deploy the Postgres Cluster with the following CR, with an example projected volume from ConfigMap.
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  description: "Example of cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.244.0.0/16 md5

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-example-app-user
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: backup-example

  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-example-superuser

  storage:
    storageClass: standard
    size: 1Gi

  projectedVolumeTemplate:
    sources:
      - configMap:
          name: sample-configmap
          items:
            - key: key1
              path: config/key1
            - key: key2
              path: config/key2

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
---
apiVersion: v1
data:
  key1: value1
  key2: value2
  key3: value3
kind: ConfigMap
metadata:
  name: sample-configmap
```

Then, delete the sources from the projectedVolumeTemplate, by setting it to `[]`. By applying the following CR:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  description: "Example of cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.244.0.0/16 md5

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-example-app-user
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: backup-example

  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-example-superuser

  storage:
    storageClass: standard
    size: 1Gi

  projectedVolumeTemplate:
    sources: []

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
---
apiVersion: v1
data:
  key1: value1
  key2: value2
  key3: value3
kind: ConfigMap
metadata:
  name: sample-configmap
```

## Relevant log output
```
{"level":"info","ts":"2023-12-20T23:55:48Z","msg":"Setting replica label","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"52cd1910-466d-4615-a76d-ede2b70bda28","uuid":"4c7ed210-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3"}
{"level":"info","ts":"2023-12-20T23:55:57Z","msg":"Pod rollout required","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"9a116368-fdbf-4d0d-95e4-37103029a72c","uuid":"51dde089-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","reason":"projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:55:57Z","msg":"Recreating instance pod","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"9a116368-fdbf-4d0d-95e4-37103029a72c","uuid":"51dde089-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","to":"ghcr.io/cloudnative-pg/postgresql:16.1","reason":"Restarting instance test-cluster-3, because: projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:56:01Z","msg":"Creating new Pod to reattach a PVC","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"6d07ca8c-ae3c-4ea0-9a37-c58186573f63","uuid":"5440e177-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","pvc":"test-cluster-3"}
{"level":"info","ts":"2023-12-20T23:56:03Z","msg":"Setting replica label","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"4069a145-058d-4016-a586-c3e3340d779d","uuid":"5572c5a2-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3"}
{"level":"info","ts":"2023-12-20T23:56:12Z","msg":"Pod rollout required","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"a7e2b8f9-0629-44be-aaec-ccfdb45d661f","uuid":"5ad221cb-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","reason":"projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:56:12Z","msg":"Recreating instance pod","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"a7e2b8f9-0629-44be-aaec-ccfdb45d661f","uuid":"5ad221cb-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","to":"ghcr.io/cloudnative-pg/postgresql:16.1","reason":"Restarting instance test-cluster-3, because: projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:56:16Z","msg":"Creating new Pod to reattach a PVC","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"ce4b29f9-1e7e-4db8-ae8f-1f31483a696a","uuid":"5d34d987-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","pvc":"test-cluster-3"}
{"level":"info","ts":"2023-12-20T23:56:18Z","msg":"Setting replica label","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"fef11604-3250-4801-88f6-71022c94ce6b","uuid":"5e66cdf2-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3"}
{"level":"info","ts":"2023-12-20T23:56:27Z","msg":"Pod rollout required","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"5053968e-143a-4a7a-ace9-d119b7074243","uuid":"63c60507-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","reason":"projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:56:27Z","msg":"Recreating instance pod","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"5053968e-143a-4a7a-ace9-d119b7074243","uuid":"63c60507-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","to":"ghcr.io/cloudnative-pg/postgresql:16.1","reason":"Restarting instance test-cluster-3, because: projected volume configuration changed, old: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}, new: &ProjectedVolumeSource{Sources:[]VolumeProjection{},DefaultMode:*420,}"}
{"level":"info","ts":"2023-12-20T23:56:31Z","msg":"Creating new Pod to reattach a PVC","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"test-cluster","namespace":"cnpg-system"},"namespace":"cnpg-system","name":"test-cluster","reconcileID":"b331d496-7a65-438a-9fc8-d2610c11b070","uuid":"6628d104-9f93-11ee-8a58-2e2e6e0be252","pod":"test-cluster-3","pvc":"test-cluster-3"}
```
