### ISSUE TITLE
Minio-operator alarm report 2

### ISSUE THREAD

**Issue by TZ-zzz** [xlab-uiuc/acto#374]
### What happened?

The operator fails to create a default `service.metadata.labels` if the field `consoleServiceLabels` is ommited in CR.

### What did you expect to happen?

The operator should add a default label to service even when users ommit the field `consoleServiceLabels` in CR.

### Root Cause

https://github.com/minio/operator/blob/master/pkg/resources/services/service.go#L90C1-L91C1. At this line, `internalLabels` are added to the varaible `labels` only when ```Spec.ServiceMetadata.ConsoleServiceLabels != nil```. And later, the variable `labels` is used to create service. Possible solution is to add the `internalLabels` to the `labels` regardless of whether the `Spec.ServiceMetadata.ConsoleServiceLabels` is nil or not. To fix this bug, simply add a else statement right after the line mentioned above.

### minimal CR to reproduce the bug
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: test-cluster
  namespace: minio-operator
  labels:
    app: minio
spec:
  features:
    bucketDNS: false
  users:
    - name: storage-user
  podManagementPolicy: Parallel
  configuration:
    name: storage-configuration
  env: [ ]
  serviceMetadata: {}
  image: quay.io/minio/minio:RELEASE.2024-02-09T21-25-16Z
  mountPath: /export
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: { }
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: standard
        status: {}
  requestAutoCert: true
```
