### ISSUE TITLE
[percona-server-mongodb-operator] Ineffective field: spec.runUid, unable to change the UID for running mongodb

### ISSUE THREAD

**Issue by tylergu** [xlab-uiuc/acto#90]
**What happened?**
We found the field spec.runUid is not effective. Changing the field does not update the UID that's used for running MongoDB.

**Did you expect to see something different?**
We expected that by setting the field `spec.runUid` to another uid, PSMDB operator would use that UID to run MongoDB. But through checking the code, we found that the field `spec.runUid` never actually gets used, and the Uid is hardcoded as 1001.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy PSMDB operator
2. Change the runUid to `1003` by applying the cr1.yaml
    <details><summary>cr1.yaml</summary>
    
      ```yaml
      apiVersion: psmdb.percona.com/v1-12-0
      kind: PerconaServerMongoDB
      metadata:
        name: minimal-cluster
      spec:
        runUid: 1003
        crVersion: 1.12.0
        image: percona/percona-server-mongodb:5.0.7-6
        allowUnsafeConfigurations: true
        upgradeOptions:
          apply: 5.0-never
          schedule: "0 2 * * *"
        secrets:
          users: minimal-cluster
        replsets:
      
        - name: rs0
          size: 1
          volumeSpec:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 3Gi
      
        sharding:
          enabled: true
      
          configsvrReplSet:
            size: 1
            volumeSpec:
              persistentVolumeClaim:
                resources:
                  requests:
                    storage: 3Gi
      
          mongos:
            size: 1
      ```

    </details>
4. Observe that the users are still `1001`

# Environment
* Kubernetes version information:

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-10T18:26:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
    
* Kubernetes cluster kind:  Kind cluster

**Anything else we need to know?**:
The root cause is inside the https://github.com/percona/percona-server-mongodb-operator/blob/5bf62ab58b58c7949c8aa7750d730a112ec69ecf/pkg/apis/psmdb/v1/psmdb_defaults.go#L580 where the fsgroup is hardcoded as `1001`. And the field `spec.runUid` is never accessed excepting setting the defaults.
